- name: cretation users et groups plus setting du password 
  hosts: dev,int
  vars_files:
    - vars.yml

  tasks: 

    - name: création des groupes 
      group: 
        state: present 
        name: continuous

    - name: creation des users + password 
      user: 
        state: present
        name: "{{ item.name }}"
        groups: "{{ item.groups}}"
        append: yes 
        password:   "{{ '{{ item.password }}' | password_hash('sha512') }}"

      loop: "{{ newusers }}"


     
